### ISSUE TITLE
Get 416 Client Error on some zip files

### ISSUE THREAD

**Issue by drygdryg** [gtsystem/python-remotezip#13]
remotezip raising `remotezip.RemoteIOError` on some files. For example, http://0x0.st/o5Pa.apk (it's unavailable for now, so I re-uploaded it to https://transfer.sh/get/rndzvr/test.apk)
Also uploaded it to GitHub as zip archive: [test.zip](https://github.com/gtsystem/python-remotezip/files/10267095/test.zip)
```
$ remotezip http://0x0.st/o5Pa.apk AndroidManifest.xml
Extracting AndroidManifest.xml...
Traceback (most recent call last):
  File "/.../venv/lib/python3.10/site-packages/remotezip.py", line 193, in fetch_fun
    res, headers = self.request(self.url, range_header, kwargs, self.session)
  File "/.../venv/lib/python3.10/site-packages/remotezip.py", line 184, in request
    res.raise_for_status()
  File "/.../venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 416 Client Error: Requested Range Not Satisfiable for url: http://0x0.st/o5Pa.apk

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.../venv/bin/remotezip", line 43, in <module>
    extract_files(args.url, args.filename, args.dir)
  File "/.../venv/bin/remotezip", line 26, in extract_files
    zip.extract(fname, path=path)
  File "/usr/lib/python3.10/zipfile.py", line 1628, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/lib/python3.10/zipfile.py", line 1698, in _extract_member
    with self.open(member, pwd=pwd) as source, \
  File "/usr/lib/python3.10/zipfile.py", line 1530, in open
    fheader = zef_file.read(sizeFileHeader)
  File "/usr/lib/python3.10/zipfile.py", line 745, in read
    data = self._file.read(n)
  File "/.../venv/lib/python3.10/site-packages/remotezip.py", line 112, in read
    self.buffer = self.fetch_fun((self.buffer.position, self.buffer.position + fetch_size -1), stream=stream)
  File "/.../venv/lib/python3.10/site-packages/remotezip.py", line 196, in fetch_fun
    raise RemoteIOError(str(e))
remotezip.RemoteIOError: 416 Client Error: Requested Range Not Satisfiable for url: http://0x0.st/o5Pa.apk
```
I also tested this file with [PartialZipBrowser](https://github.com/tihmstar/partialZipBrowser), and it works fine:
```
$ pzb -g AndroidManifest.xml https://0x0.st/o5Pa.apk
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: https://0x0.st/o5Pa.apk
init done
getting: AndroidManifest.xml
100% [===================================================================================================>]
download succeeded
```

It looks like byte range calculation bug in remotezip.
I also sniffed traffic, generated by remotezip and PartialZibBrowser while downloading this file, in mitmproxy, this may help you.
1. remotezip
![image](https://user-images.githubusercontent.com/43933400/208459898-d62dd2ad-1fd3-40d8-85c5-df2416a06144.png)
2. PartialZipBrowser:
![image](https://user-images.githubusercontent.com/43933400/208460225-12c31661-f2ed-44c7-b412-de6ba7bc2aca.png)

**Comment by drygdryg** [comment]
It looks like some pos2size values in `RemoteZip` class are calculated incorrectly.

https://github.com/gtsystem/python-remotezip/blob/8d6634cc51e127afb7a9704c364f4fa136b5fd8d/remotezip.py#L218-L228
![image](https://user-images.githubusercontent.com/43933400/208627538-c8c3d9ce-6f42-4e89-ba40-2c79ab74dcce.png)

Perhaps it will be enough to change this line:
https://github.com/gtsystem/python-remotezip/blob/8d6634cc51e127afb7a9704c364f4fa136b5fd8d/remotezip.py#L226
to:
```python
position_to_size[m1.header_offset] = abs(m2.header_offset - m1.header_offset)
```

**Comment by gtsystem** [comment]
Thanks @drygdryg, your analysis was very helpful to find the issue. Please test if version 0.11.1 solve the issue.

**Comment by drygdryg** [comment]
Tested on ~2800 zip files, everything works fine. Thanks for the quick fix!
