### ISSUE TITLE
Adding remotezip to conda-forge

### ISSUE THREAD

**Issue by jhkennedy** [gtsystem/python-remotezip#18]
:wave: remotezip team! We've been using remotezip with great success in one of our packages, so first of all, thank you very much.

We'd like to distribute our package on conda-forge, and as such, we need a conda-forge build of remotezip. I've gone ahead and made the recipe, opened the PR, and volunteered to maintain the recipe: https://github.com/conda-forge/staged-recipes/pull/22535

I'm happy to either (1) do that solo or (2) add anyone from here as a maintainer if they're interested. Just let me know if you are!

**Comment by gtsystem** [comment]
Hi @jhkennedy, thanks for contributing this recipe. I'm happy if you take care of it going forward :)

**Comment by jhkennedy** [comment]
@gtsystem sounds good! I'm happy to do so.

For posterity, if anyone does end up wanting to add themselves to the maintainer list, the instructions are here:
https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-the-maintainer-list
