### ISSUE TITLE
Please add wheel for v0.12.x

### ISSUE THREAD

**Issue by edek437** [gtsystem/python-remotezip#22]
Hi,

Thank you for this library. I can see that there is no wheel for 0.12.0, 0.12.1, 0.12.2.
Would you be able to upload one?

It seem that from pip23.1 wheels or pyproject.toml would be required to install package. I got below deprecation warning when installing remotezip.

11:56:47   DEPRECATION: remotezip is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

Thanks 😃

**Comment by gtsystem** [comment]
Hi, thanks for bringing this up. I uploaded the wheel version for v0.12.2 https://pypi.org/project/remotezip/0.12.2/#files

Hope this helps

**Comment by edek437** [comment]
Hi,
thanks. Yes it helps.
