### ISSUE TITLE
feature request: file size of remote zip file

### ISSUE THREAD

**Issue by relikd** [gtsystem/python-remotezip#24]
Unfortunatelly summing up all uncompressed sizes of all zipped entries is not equivalent to the filesize if I were to download a zip file. I guess thats because the zip file itself has metadata etc.
Therefore, I would like to store the file size of the remote file and make it available to the RemoteZip class. I think this should be the output of `RemoteFetcher.get_file_size()`?

**Comment by relikd** [comment]
But unfortunately this results in the same problem I had while searching for a manual solution. It does not handle redirects well. HEAD will have no content-length on HTTP 304.

**Comment by relikd** [comment]
`zip.fp.tell()` seems to work, though I dont know if `tell` is available in all cases and if it will always be EOF?

**Comment by gtsystem** [comment]
Correct file size can be found in `zip.fp._file_size`. I suppose we could expose this under `zip.size()`. Would you like to provide a PR?
