### ISSUE TITLE
No wheel for v0.9.3

### ISSUE THREAD

**Issue by domdfcoding** [gtsystem/python-remotezip#5]
Hi,

Thank you for this library. I can see that there are wheels on PyPI for `0.9.2` and `0.9.1`, but there's no wheel for `0.9.3`. 
Would you be able to upload one?

Thanks 😃

**Comment by gtsystem** [comment]
Wheel uploaded, thanks for bringing this up.

**Comment by domdfcoding** [comment]
Wonderful, thanks
